version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # 8000번 포트로 변경
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=8000  # 8000번 포트로 변경
